apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-deployment
  labels:
    app: flutter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flutter
  template:
    metadata:
      labels:
        app: flutter
    spec:
      containers:
      - name: flutter-web
        image: flutter-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flutter-service
spec:
  selector:
    app: flutter
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 31000
    type: NodePort