name: CI
on: [push]

jobs:
  build_web:
    name: Build Flutter (Web)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
      - run: | 