name: CI
on: [push]

jobs:
  # flutter_test:
  #   name: Test
  #   runs-on: self-hosted      
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-java@v1
  #       with:
  #         java-version: "12.x"
  #     - uses: subosito/flutter-action@v1
  #       with:
  #         channel: "stable"
  #     - run: flutter pub get
  #     - run: flutter analyze
  #     - run: flutter test

  build_notification:
    name: Build Notification
    # needs: [flutter_test]
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Build Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#flutter-sample'
        message: Starting Flutter Build
      if: always()

  flutter_build:
    name: Build
    needs: [build_notification]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          docker build -t flutter-web .
      - run: |
          docker run -d -p 8080:80 --name flutter-web flutter-web 

  deploy_notification:
    name: Deploy Notification
    needs: [flutter_build]
    runs-on: self-hosted
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Slack Notification
      uses: act10ns/slack@v1
      with: 
        status: starting
        channel: '#flutter-sample'
        message: Starting Flutter Deploy
      if: always()

  flutter_deploy:
    name: Deploy
    needs: [deploy_notification]
    runs-on: self-hosted
    steps:
      - run: docker --version
      - run: kubectl get po -A
      - run: kubectl cluster-info
      - run: kubectl get nodes
      - run: kubeclt apply -f deploy/deployment.yaml
      - run: kubectl get po -A
      - run: kubectl cluster-info
      - run: kubectl get nodes
      - run: echo 'http://20.163.118.138:8080'